"""
LEDGER — Copilot Router
Grounded, bounded decision support. The LLM explains — it never decides.
"""
from __future__ import annotations

import time
import uuid
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.security import CurrentUser, require_underwriter
from app.copilot.providers import get_llm_provider
from app.copilot.tools import (
    get_credit_pathway,
    get_customer_profile,
    get_financial_evidence,
    get_model_explanation,
    get_next_best_evidence,
    get_recent_events,
    get_uncertainty,
)
from app.models.models import AuditEvent, CopilotInteraction
from app.rag.retriever import build_grounded_prompt, retrieve_relevant_chunks

router = APIRouter()


class CopilotQueryRequest(BaseModel):
    query: str = Field(min_length=5, max_length=1000)
    application_id: UUID | None = None

    class Config:
        json_schema_extra = {
            "example": {
                "query": "Why did the credit assessment change after the income event?",
                "application_id": "uuid-here",
            }
        }


class CopilotResponse(BaseModel):
    response: str
    citations: list[dict]
    tools_called: list[str]
    llm_provider: str
    is_mock: bool
    latency_ms: int
    interaction_id: str
    disclaimer: str = (
        "This explanation is generated by an AI copilot grounded in retrieved evidence and "
        "policy documents. The credit pathway was determined by the XGBoost Decision Engine, "
        "not this copilot. Final decisions remain with the underwriter."
    )


@router.post("/query", response_model=CopilotResponse)
async def query_copilot(
    body: CopilotQueryRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[CurrentUser, Depends(require_underwriter)],
):
    """
    Ask the bounded Decision Support Copilot a question.

    The copilot:
    1. Retrieves relevant policy chunks (RAG)
    2. Calls bounded read-only tools for ML context
    3. Constructs a grounded prompt
    4. Generates a cited explanation via Ollama or MockProvider
    5. Logs the interaction for governance
    """
    start = time.monotonic()

    # ── Step 1: RAG retrieval ─────────────────────────────────────────────
    retrieved_chunks = []
    try:
        retrieved_chunks = await retrieve_relevant_chunks(db, body.query, top_k=5)
    except Exception as e:
        # RAG failure is non-fatal — proceed with tool context only
        retrieved_chunks = []

    # ── Step 2: Gather tool context ───────────────────────────────────────
    tool_results = {}
    tools_called = []

    if body.application_id:
        app_id = body.application_id

        profile = await get_customer_profile(db, app_id)
        tool_results["customer_profile"] = profile
        tools_called.append("get_customer_profile")

        evidence = await get_financial_evidence(db, app_id)
        tool_results["financial_evidence"] = evidence
        tools_called.append("get_financial_evidence")

        explanation = await get_model_explanation(db, app_id)
        tool_results["model_explanation"] = explanation
        tools_called.append("get_model_explanation")

        pathway = await get_credit_pathway(db, app_id)
        tool_results["credit_pathway"] = pathway
        tools_called.append("get_credit_pathway")

        uncertainty = await get_uncertainty(db, app_id)
        tool_results["uncertainty"] = uncertainty
        tools_called.append("get_uncertainty")

        events = await get_recent_events(db, app_id)
        tool_results["recent_events"] = events
        tools_called.append("get_recent_events")

    # ── Step 3: Build grounded prompt ─────────────────────────────────────
    # ANTI-INJECTION: user query is wrapped as untrusted data
    system_prompt, user_message = build_grounded_prompt(
        query=body.query,
        retrieved_chunks=retrieved_chunks,
        tool_results=tool_results,
    )

    # ── Step 4: LLM generation ────────────────────────────────────────────
    # Build context dict for MockProvider (uses real ML values)
    context = {
        "retrieved_chunks": retrieved_chunks,
        "risk_probability": tool_results.get("model_explanation", {}).get("risk_probability"),
        "confidence": tool_results.get("model_explanation", {}).get("confidence"),
        "shap_values": tool_results.get("model_explanation", {}).get("shap_values", {}),
        "pathway": tool_results.get("credit_pathway", {}),
        "features": tool_results.get("financial_evidence", {}).get("features", {}),
    }

    provider = get_llm_provider()
    llm_response = await provider.generate(
        system_prompt=system_prompt,
        user_message=user_message,
        context=context,
    )

    latency_ms = int((time.monotonic() - start) * 1000)

    # ── Step 5: Guardrail — verify no hallucinated numbers ─────────────────
    _guardrail_check(llm_response.content, tool_results)

    # ── Step 6: Log interaction ───────────────────────────────────────────
    interaction_id = str(uuid.uuid4())
    interaction = CopilotInteraction(
        application_id=body.application_id,
        user_id=uuid.UUID(current_user.user_id),
        query=body.query[:1000],  # Truncate for storage
        retrieved_chunks=[
            {"id": c["chunk_id"], "title": c["title"], "similarity": c["similarity"]}
            for c in retrieved_chunks[:3]
        ],
        tool_calls=tools_called,
        response=llm_response.content[:2000],
        llm_provider=llm_response.provider,
        latency_ms=latency_ms,
    )
    db.add(interaction)

    if body.application_id:
        db.add(AuditEvent(
            application_id=body.application_id,
            event_type="copilot_queried",
            actor=f"underwriter:{current_user.email}",
            payload={"query_preview": body.query[:100], "tools_called": tools_called},
        ))

    return CopilotResponse(
        response=llm_response.content,
        citations=retrieved_chunks[:3],
        tools_called=tools_called,
        llm_provider=llm_response.provider,
        is_mock=llm_response.is_mock,
        latency_ms=latency_ms,
        interaction_id=interaction_id,
    )


def _guardrail_check(response: str, tool_results: dict) -> None:
    """
    Simple numeric guardrail: flag if response contains numbers not from tool results.
    Logs a warning but does not block (graceful degradation for prototype).
    """
    import re
    import structlog
    log = structlog.get_logger()

    # Extract all numbers from response
    response_numbers = set(re.findall(r"\b\d+\.?\d*\b", response))

    # Extract all numbers from tool results
    tool_numbers = set(re.findall(r"\b\d+\.?\d*\b", str(tool_results)))

    # Flag numbers in response not present in tools
    potentially_hallucinated = response_numbers - tool_numbers - {
        "0", "1", "2", "3", "10", "100"  # Common safe numerals
    }

    if potentially_hallucinated and len(potentially_hallucinated) > 3:
        log.warning(
            "copilot_potential_hallucination",
            flagged_numbers=list(potentially_hallucinated)[:5],
            note="Guardrail detected numbers not in tool results. Response not blocked in prototype.",
        )
